"""Add difficulty column to Score

Revision ID: b5a77f688dd2
Revises: 
Create Date: 2024-12-07 18:45:16.012247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a77f688dd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        # Add difficulty column with a default value and allow NOT NULL
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=False, server_default='easy'))

    # Remove the server default after the column is added (optional cleanup step)
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('difficulty', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
